# LLVM MIR P4：使用 P4 fork 工具链中的 llc。

compilers=p4-mir-llc
defaultCompiler=p4-mir-llc
supportsExecute=false

objdumper=/opt/compiler-explorer/p4-latest/bin/llvm-objdump
demangler=/opt/compiler-explorer/p4-latest/bin/llvm-cxxfilt

compiler.p4-mir-llc.exe=/opt/compiler-explorer/p4-latest/bin/llc
compiler.p4-mir-llc.name=P4 llc (latest)
compiler.p4-mir-llc.isSemVer=false
compiler.p4-mir-llc.semver=(fork)
compiler.p4-mir-llc.compilerType=llc
compiler.p4-mir-llc.groupName=LLVM P4
compiler.p4-mir-llc.versionRe=LLVM version .*
