# LLVM IR P4：与 LLVM IR 同模式，编译器为 P4 修改版 LLVM 的 opt 与 llc，路径走稳定软链 p4-latest。

compilers=p4opt:p4llc
defaultCompiler=p4opt
supportsExecute=false

objdumper=/opt/compiler-explorer/p4-latest/bin/llvm-objdump
demangler=/opt/compiler-explorer/p4-latest/bin/llvm-cxxfilt

# opt：LLVM IR 优化器。
compiler.p4opt.exe=/opt/compiler-explorer/p4-latest/bin/opt
compiler.p4opt.name=P4 opt (latest)
compiler.p4opt.isSemVer=false
compiler.p4opt.semver=(fork)
compiler.p4opt.compilerType=opt
compiler.p4opt.supportsBinary=false
compiler.p4opt.instructionSet=llvm
compiler.p4opt.groupName=LLVM P4
compiler.p4opt.versionRe=LLVM version .*

# llc：LLVM IR 静态编译器。
compiler.p4llc.exe=/opt/compiler-explorer/p4-latest/bin/llc
compiler.p4llc.name=P4 llc (latest)
compiler.p4llc.isSemVer=false
compiler.p4llc.semver=(fork)
compiler.p4llc.compilerType=llc
compiler.p4llc.groupName=LLVM P4
compiler.p4llc.versionRe=LLVM version .*
compiler.p4llc.intelAsm=--x86-asm-syntax=intel
