# LLVM MIR：复用 clang-latest 中的 llc。

compilers=&llc
defaultCompiler=mir-llc
supportsExecute=false

objdumper=/opt/compiler-explorer/clang-latest/bin/llvm-objdump
demangler=/opt/compiler-explorer/clang-latest/bin/llvm-cxxfilt

group.llc.compilers=mir-llc
group.llc.compilerType=llc
group.llc.supportsExecute=false
group.llc.groupName=LLVM Static Compiler
group.llc.baseName=llc
group.llc.isSemVer=true
group.llc.versionRe=LLVM version .*
group.llc.intelAsm=-masm=intel

compiler.mir-llc.exe=/opt/compiler-explorer/clang-latest/bin/llc
compiler.mir-llc.semver=22.1.8
