# LLVM MIR：复用 clang-latest 中的 llc。

compilers=mir-llc
defaultCompiler=mir-llc
supportsExecute=false

objdumper=/opt/compiler-explorer/clang-latest/bin/llvm-objdump
demangler=/opt/compiler-explorer/clang-latest/bin/llvm-cxxfilt

compiler.mir-llc.exe=/opt/compiler-explorer/clang-latest/bin/llc
compiler.mir-llc.name=llc 22.1.8
compiler.mir-llc.semver=22.1.8
compiler.mir-llc.compilerType=llc
compiler.mir-llc.groupName=LLVM Static Compiler
compiler.mir-llc.versionRe=LLVM version .*
compiler.mir-llc.intelAsm=-masm=intel
